/** @file common.c @brief Shared command helpers and registration. */
#include "commands.h"
#include "ban_db.h"
#include "chanserv_db.h"
#include "config.h"
#include "geoip.h"
#include "numerics.h"
#include <stdio.h>
#include <sys/socket.h>
#include <time.h>
const char*command_reply_nick(const Client*c){return !c||!c->nick[0]?"*":c->nick;}
static int registration_banned(Server*s,Client*c){BanDb db={0};BanRecord r;char h[IRCD_MESSAGE_BUFFER_SIZE],ip[IRCD_MESSAGE_BUFFER_SIZE];const char*rh=NULL;int m=0;if(ban_db_open(&db,s->config.bans_db)!=0)return 0;if(ban_db_match(&db,BAN_TYPE_ZLINE,c->real_ip,NULL,&r)==1)m=1;else{if(c->real_host[0]){snprintf(h,sizeof(h),"%s@%s",c->user,c->real_host);rh=h;}snprintf(ip,sizeof(ip),"%s@%s",c->user,c->real_ip);if(ban_db_match(&db,BAN_TYPE_KLINE,rh?rh:ip,ip,&r)==1)m=1;}if(m){client_sendf(c,ERR_YOUREBANNEDCREEP,s->config.server_name,command_reply_nick(c),s->config.admin_email);snprintf(c->quit_reason,sizeof(c->quit_reason),"%s",r.reason[0]?r.reason:"Banned");shutdown(c->fd,SHUT_RDWR);}ban_db_close(&db);return m;}
void command_maybe_register(Server*s,Client*c){char is[IRCD_MESSAGE_BUFFER_SIZE],pc[IRCD_MESSAGE_BUFFER_SIZE/2]="";ChanServDb cs={0};if(!s||!c||c->registered||!c->nick[0]||!c->user[0]||c->cap_negotiating||c->dns_state==CLIENT_DNS_PENDING||c->dns_state==CLIENT_DNS_NONE||(s->config.server_password[0]&&!c->pass_accepted))return;if(!c->geoip_complete){geoip_lookup(&s->geoip,c->real_ip,&c->geoip);c->geoip_complete=1;}if(c->dnsbl_state==CLIENT_DNSBL_NONE){if(!s->config.dnsbl_count)c->dnsbl_state=CLIENT_DNSBL_CLEAR;else if(dnsbl_resolver_submit(&s->dnsbl,c->id,c->real_ip,s->config.dnsbls,s->config.dnsbl_count)==0){c->dnsbl_state=CLIENT_DNSBL_PENDING;c->dnsbl_deadline=time(NULL)+(time_t)s->config.dnsbl_timeout_seconds;return;}else c->dnsbl_state=CLIENT_DNSBL_ERROR;}if(c->dnsbl_state==CLIENT_DNSBL_PENDING||c->dnsbl_state==CLIENT_DNSBL_LISTED)return;if(registration_banned(s,c))return;c->registered=1;client_sendf(c,RPL_WELCOME,s->config.server_name,c->nick,s->config.network_name,c->nick,c->user,c->display_host);client_sendf(c,RPL_YOURHOST,s->config.server_name,c->nick,s->config.server_name,IRCD_VERSION);client_sendf(c,RPL_CREATED,s->config.server_name,c->nick,IRCD_CREATED);client_sendf(c,RPL_AVAILABLE,s->config.server_name,c->nick,s->config.server_name,IRCD_VERSION,IRCD_SUPPORTED_USER_MODES,IRCD_SUPPORTED_CHANNEL_MODES);if(chanserv_db_open(&cs,s->config.chanserv_db)==0){chanserv_db_list_enabled(&cs,pc,sizeof(pc));chanserv_db_close(&cs);}snprintf(is,sizeof(is),"%s CHATHISTORY=%zu PCHANNELS=%s",IRCD_ISUPPORT_BASE,s->config.history_limit,pc);client_sendf(c,RPL_PROTOCOLS,s->config.server_name,c->nick,is);}
int command_require_registered(Client*c){if(c&&c->registered)return 0;if(c)client_sendf(c,ERR_NOTREGISTERED,IRCD_DEFAULT_SERVER_NAME,command_reply_nick(c));return 1;}
void command_send_names(Channel*ch,Client*c){char n[IRC_NAMES_BUFFER_SIZE];size_t u=0;ChannelMember*m;char mark;if(!ch||!c)return;mark=ch->name[0]=='&'?IRC_NAMES_PRIVATE_MARKER:IRC_NAMES_PUBLIC_MARKER;n[0]='\0';for(m=ch->members;m;m=m->next){char p=channel_privilege_prefix(m->privileges);int w=p?snprintf(n+u,sizeof(n)-u,"%s%c%s",u?" ":"",p,m->client->nick):snprintf(n+u,sizeof(n)-u,"%s%s",u?" ":"",m->client->nick);if(w<0||(size_t)w>=sizeof(n)-u)break;u+=(size_t)w;}client_sendf(c,RPL_NAMREPLY,IRCD_DEFAULT_SERVER_NAME,c->nick,mark,ch->name,n);client_sendf(c,RPL_ENDOFNAMES,IRCD_DEFAULT_SERVER_NAME,c->nick,ch->name);}
