/** @file moderation_policy.c @brief PRIVMSG/NOTICE policy wrapper. */
#include "commands.h"
#include "channel_policy.h"
#include "config.h"
#include "modes.h"
#include "nospoof.h"
#include "numerics.h"
#include <stdio.h>
#include <string.h>
CommandResult command_privmsg_core(Server *,Client *,char *);CommandResult command_notice_core(Server *,Client *,char *);
static int is_oper_or_above(const Client *client){return client!=NULL&&client_mode_has(client->modes,CLIENT_MODE_OPER|CLIENT_MODE_NETADMIN);}
static char *message_target(char *copy){return copy==NULL?NULL:strtok(copy," ");}
static int version_blocks_private(Server *server,Client *sender,const char *target){Client *destination;if(!nospoof_version_restricted(server,sender)||target==NULL||strchr(IRC_CHANNEL_PREFIXES,target[0])!=NULL)return 0;destination=hash_get(&server->clients_by_nick,target);if(destination==NULL)return 0;if(is_oper_or_above(destination))return 0;client_sendf(sender,":%s NOTICE %s :You must respond to the CTCP VERSION request before sending private messages.",server->config.server_name,sender->nick);return 1;}
static int muted_channel_send(Server *server,Client *client,const char *target){Channel *channel;ChannelMember *member;if(target==NULL||strchr(IRC_CHANNEL_PREFIXES,target[0])==NULL)return 0;if(!client_mode_has(client->modes,CLIENT_MODE_CHANNEL_MUTE)||is_oper_or_above(client))return 0;channel=hash_get(&server->channels_by_name,target);if(channel!=NULL){member=channel_find_member(channel,client);if(member!=NULL&&member->privileges!=0U)return 0;}client_sendf(client,ERR_CANNOTSENDTOCHAN,server->config.server_name,client->nick,target,"channel messaging disabled by user mode +M");return 1;}
static int banned_channel_send(Server *server,Client *client,const char *target,int notice){Channel *channel;ChannelMember *member;int banned;if(target==NULL||strchr(IRC_CHANNEL_PREFIXES,target[0])==NULL)return 0;channel=hash_get(&server->channels_by_name,target);if(channel==NULL)return 0;member=channel_find_member(channel,client);if(member!=NULL&&channel_privilege_has(member->privileges,CHANNEL_PRIV_OWNER))return 0;if(member!=NULL&&channel_privilege_has(member->privileges,CHANNEL_PRIV_PROTECTED))banned=channel_client_is_banned_protected(channel,client);else banned=channel_client_is_banned(channel,client);if(!banned)return 0;if(!notice)client_sendf(client,ERR_CANNOTSENDTOCHAN,server->config.server_name,client->nick,channel->name,"banned from channel (+b)");return 1;}
static int private_deaf_blocks_privmsg(Server *server,Client *sender,const char *target_name){Client *destination;if(target_name==NULL||strchr(IRC_CHANNEL_PREFIXES,target_name[0])!=NULL)return 0;destination=hash_get(&server->clients_by_nick,target_name);if(destination==NULL)return 0;if(client_mode_has(destination->modes,CLIENT_MODE_PRIVATE_DEAF)&&!is_oper_or_above(sender)){client_sendf(sender,":%s!%s@%s NOTICE %s :I cannot send or receive private messages.",destination->nick,destination->user,destination->display_host,sender->nick);return 1;}if(client_mode_has(sender->modes,CLIENT_MODE_PRIVATE_DEAF)&&!is_oper_or_above(destination))return 1;return 0;}
static int private_deaf_blocks_notice(Server *server,Client *sender,const char *target_name){Client *destination;if(target_name==NULL||strchr(IRC_CHANNEL_PREFIXES,target_name[0])!=NULL)return 0;destination=hash_get(&server->clients_by_nick,target_name);if(destination==NULL)return 0;if(client_mode_has(destination->modes,CLIENT_MODE_PRIVATE_DEAF)&&!is_oper_or_above(sender))return 1;if(client_mode_has(sender->modes,CLIENT_MODE_PRIVATE_DEAF)&&!is_oper_or_above(destination))return 1;return 0;}
CommandResult command_privmsg(Server *server,Client *client,char *params){char copy[IRCD_MESSAGE_BUFFER_SIZE];char *target;if(params==NULL)return command_privmsg_core(server,client,params);(void)snprintf(copy,sizeof(copy),"%s",params);target=message_target(copy);if(version_blocks_private(server,client,target))return COMMAND_KEEP_CLIENT;if(banned_channel_send(server,client,target,0))return COMMAND_KEEP_CLIENT;if(muted_channel_send(server,client,target))return COMMAND_KEEP_CLIENT;if(private_deaf_blocks_privmsg(server,client,target))return COMMAND_KEEP_CLIENT;return command_privmsg_core(server,client,params);}
CommandResult command_notice(Server *server,Client *client,char *params){char copy[IRCD_MESSAGE_BUFFER_SIZE];char *target;if(params!=NULL&&nospoof_handle_notice(server,client,params))return COMMAND_KEEP_CLIENT;if(params==NULL)return command_notice_core(server,client,params);(void)snprintf(copy,sizeof(copy),"%s",params);target=message_target(copy);if(banned_channel_send(server,client,target,1))return COMMAND_KEEP_CLIENT;if(muted_channel_send(server,client,target))return COMMAND_KEEP_CLIENT;if(private_deaf_blocks_notice(server,client,target))return COMMAND_KEEP_CLIENT;return command_notice_core(server,client,params);}
