/** @file oper.c @brief IRC OPER authentication for bootstrap netadmin and SQLite operators. */
#include "commands.h"
#include "auth_limit.h"
#include "channel_policy.h"
#include "modes.h"
#include "numerics.h"
#include "oper.h"
#include "operator_db.h"

#include <argon2.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>

static int netadmin_host_matches(const Client *client,const char *mask){char host_identity[IRCD_MESSAGE_BUFFER_SIZE];char ip_identity[IRCD_MESSAGE_BUFFER_SIZE];if(client==NULL||mask==NULL||*mask=='\0')return 0;if(client->real_host[0]!='\0'){(void)snprintf(host_identity,sizeof(host_identity),"%s!%s@%s",client->nick,client->user,client->real_host);if(irc_mask_match(mask,host_identity))return 1;}(void)snprintf(ip_identity,sizeof(ip_identity),"%s!%s@%s",client->nick,client->user,client->real_ip);return irc_mask_match(mask,ip_identity);}
static void grant_oper(Client *client,const char *name,OperPermissionSet permissions,const char *vhost){client->oper_permissions=permissions;(void)snprintf(client->oper_name,sizeof(client->oper_name),"%s",name);client->modes=client_mode_add(client->modes,CLIENT_MODE_OPER);client->snotice_mask=SNOTICE_ALL;if(oper_permission_has(permissions,OPER_PERMISSION_NETADMIN))client->modes=client_mode_add(client->modes,CLIENT_MODE_NETADMIN);if(oper_permission_has(permissions,OPER_PERMISSION_HELPOP))client->modes=client_mode_add(client->modes,CLIENT_MODE_HELPOP);if(oper_permission_has(permissions,OPER_PERMISSION_GETHOST)&&vhost!=NULL&&*vhost!='\0'){(void)snprintf(client->display_host,sizeof(client->display_host),"%s",vhost);client->account_vhost_active=0;client->modes=client_mode_remove(client->modes,CLIENT_MODE_CLOAKED);client->modes=client_mode_add(client->modes,CLIENT_MODE_VHOST);}}
static void failed_oper(Server *server,Client *client,const char *name,const char *why){snotice_broadcast(server,SNOTICE_OPERATORS,"Failed OPER: %s!%s@%s [real_ip=%s] name=%s (%s)",client->nick,client->user,client->display_host,client->real_ip,name!=NULL?name:"",why);}

CommandResult command_oper(Server *server,Client *client,char *params){char *name;char *password;if(command_require_registered(client))return COMMAND_KEEP_CLIENT;if(params==NULL){client_sendf(client,ERR_NEEDMOREPARAMS,server->config.server_name,client->nick,"OPER");return COMMAND_KEEP_CLIENT;}name=strtok(params," ");password=strtok(NULL,"");if(password!=NULL&&*password==':')++password;if(name==NULL||password==NULL||*password=='\0'){client_sendf(client,ERR_NEEDMOREPARAMS,server->config.server_name,client->nick,"OPER");return COMMAND_KEEP_CLIENT;}
if(server->config.netadmin_name[0]!='\0'&&strcasecmp(name,server->config.netadmin_name)==0){if(server->config.netadmin_password_hash[0]=='\0'||!netadmin_host_matches(client,server->config.netadmin_hostmask)){failed_oper(server,client,name,"host not authorized");client_sendf(client,ERR_NOOPERHOST,server->config.server_name,client->nick);return COMMAND_KEEP_CLIENT;}if(!auth_limit_consume(server,client,"OPER netadmin")){failed_oper(server,client,name,"authentication throttled");client_sendf(client,ERR_PASSWDMISMATCH,server->config.server_name,client->nick);return COMMAND_KEEP_CLIENT;}if(argon2id_verify(server->config.netadmin_password_hash,password,strlen(password))!=ARGON2_OK){failed_oper(server,client,name,"bad password");client_sendf(client,ERR_PASSWDMISMATCH,server->config.server_name,client->nick);return COMMAND_KEEP_CLIENT;}grant_oper(client,server->config.netadmin_name,OPER_PERMISSION_ALL,server->config.netadmin_vhost);client_sendf(client,RPL_YOUREOPER,server->config.server_name,client->nick," Network Administrator");snotice_broadcast(server,SNOTICE_OPERATORS,"OPER successful: %s!%s@%s [real_ip=%s] as Network Administrator %s",client->nick,client->user,client->display_host,client->real_ip,client->oper_name);return COMMAND_KEEP_CLIENT;}
{
OperatorDb db;OperatorRecord record;OperPermissionSet permissions;int found;if(operator_db_open(&db,server->config.operators_db)!=0){failed_oper(server,client,name,"operator database unavailable");client_sendf(client,ERR_NOPRIVILEGES,server->config.server_name,client->nick);return COMMAND_KEEP_CLIENT;}found=operator_db_get(&db,name,&record);operator_db_close(&db);if(found!=1||!record.enabled){failed_oper(server,client,name,"unknown or disabled operator");client_sendf(client,ERR_NOOPERHOST,server->config.server_name,client->nick);return COMMAND_KEEP_CLIENT;}if(!auth_limit_consume(server,client,"OPER")){failed_oper(server,client,name,"authentication throttled");client_sendf(client,ERR_PASSWDMISMATCH,server->config.server_name,client->nick);return COMMAND_KEEP_CLIENT;}if(argon2id_verify(record.password_hash,password,strlen(password))!=ARGON2_OK){failed_oper(server,client,name,"bad password");client_sendf(client,ERR_PASSWDMISMATCH,server->config.server_name,client->nick);return COMMAND_KEEP_CLIENT;}if(oper_permissions_parse(record.permissions,&permissions)!=0||oper_permission_has(permissions,OPER_PERMISSION_NETADMIN)){failed_oper(server,client,name,"invalid stored permissions");client_sendf(client,ERR_NOPRIVILEGES,server->config.server_name,client->nick);return COMMAND_KEEP_CLIENT;}grant_oper(client,record.name,permissions,record.vhost);client_sendf(client,RPL_YOUREOPER,server->config.server_name,client->nick,"n IRC operator");snotice_broadcast(server,SNOTICE_OPERATORS,"OPER successful: %s!%s@%s [real_ip=%s] as %s",client->nick,client->user,client->display_host,client->real_ip,client->oper_name);}
return COMMAND_KEEP_CLIENT;}
