#ifndef IRCD_CONFIG_H
#define IRCD_CONFIG_H

/*
 * config.h
 *
 * Compile-time limits and safe defaults for ScratchIRCd.
 */

#define IRCD_DEFAULT_SERVER_NAME "scratch.local"
#define IRCD_DEFAULT_NETWORK_NAME "ScratchNet"
#define IRCD_VERSION "ScratchIRCd-0.18"
#define IRCD_CREATED "August 2026"
#define IRCD_DEFAULT_PORT "6667"
#define IRCD_DEFAULT_TLS_PORT "6697"
#define IRCD_DEFAULT_BIND_ADDRESS ""
#define IRCD_DEFAULT_MAX_CLIENTS 1024U
#define IRCD_HARD_MAX_CLIENTS 65535U
#define IRCD_LISTEN_BACKLOG 128
#define IRCD_MAX_LISTENERS 16U
#define IRCD_CLIENT_HASH_BUCKETS 4093U
#define IRCD_CHANNEL_HASH_BUCKETS 4093U
#define IRCD_OUTPUT_BUFFER_SIZE 1024U
#define IRCD_MESSAGE_BUFFER_SIZE 1024U
#define IRCD_NETWORK_NAME_MAX 63U
#define IRCD_PORT_TEXT_MAX 15U
#define IRCD_CONFIG_LINE_MAX 1024U
#define IRCD_CONFIG_PATH_MAX 511U
#define IRCD_SERVER_PASSWORD_MAX 127U
#define IRCD_ADMIN_TEXT_MAX 255U
#define IRCD_DEFAULT_CONFIG_FILE "ircd.conf"
#define IRCD_DEFAULT_MOTD_FILE "motd.txt"
#define IRCD_DEFAULT_RULES_FILE "rules.txt"
#define IRCD_DEFAULT_DATA_DIR "data"
#define IRCD_DEFAULT_OPERATORS_DB IRCD_DEFAULT_DATA_DIR "/operators.db"
#define IRCD_DEFAULT_BANS_DB IRCD_DEFAULT_DATA_DIR "/bans.db"
#define IRCD_DEFAULT_NICKSERV_DB IRCD_DEFAULT_DATA_DIR "/nickserv.db"
#define IRCD_DEFAULT_CHANSERV_DB IRCD_DEFAULT_DATA_DIR "/chanserv.db"
#define IRCD_DEFAULT_HISTORY_DB IRCD_DEFAULT_DATA_DIR "/history.db"
#define IRCD_DEFAULT_GEOIP_CITY_DB IRCD_DEFAULT_DATA_DIR "/GeoLite2-City.mmdb"
#define IRCD_DEFAULT_GEOIP_ASN_DB IRCD_DEFAULT_DATA_DIR "/GeoLite2-ASN.mmdb"
#define IRCD_DEFAULT_DNS_TIMEOUT_SECONDS 5U
#define IRCD_DEFAULT_DNSBL_TIMEOUT_SECONDS 5U
#define IRCD_DEFAULT_HISTORY_LIMIT 100U
#define IRCD_HISTORY_HARD_LIMIT 500U
#define IRCD_HISTORY_TEXT_MAX 510U
#define IRCD_HISTORY_COMMAND_MAX 15U
#define IRCD_HISTORY_BATCH_ID_MAX 31U

/* ChanServ registration limits. */
#define IRCD_CHANSERV_DESCRIPTION_MAX 255U

/* NickServ account recovery and outbound-mail limits. */
#define IRCD_EMAIL_MAX 254U
#define IRCD_MAIL_SUBJECT_MAX 127U
#define IRCD_MAIL_BODY_MAX 1023U
#define IRCD_RESET_TOKEN_BYTES 16U
#define IRCD_RESET_TOKEN_HEX_LEN (IRCD_RESET_TOKEN_BYTES * 2U)
#define IRCD_TOKEN_HASH_HEX_LEN 64U
#define IRCD_DEFAULT_NICKSERV_RESET_SECONDS 1800U
#define IRCD_DEFAULT_NICKSERV_VERIFY_SECONDS 86400U
#define IRCD_DEFAULT_SENDMAIL_PATH ""

/* DNS blacklist definitions. Kept small enough for atomic Linux pipe writes. */
#define IRCD_MAX_DNSBLS 8U
#define IRCD_DNSBL_NAME_MAX 63U
#define IRCD_DNSBL_ZONE_MAX 255U

/* GeoIP fields retained on Client.geoip. */
#define IRCD_GEOIP_STATUS_MAX 31U
#define IRCD_GEOIP_NETWORK_MAX 63U
#define IRCD_GEOIP_SOURCE_MAX 63U
#define IRCD_GEOIP_CODE_MAX 7U
#define IRCD_GEOIP_REGION_CODE_MAX 7U
#define IRCD_GEOIP_NAME_MAX 127U
#define IRCD_GEOIP_ORG_MAX 255U

/* Authorized WebIRC gateways. */
#define IRCD_MAX_WEBIRC_GATEWAYS 16U
#define IRCD_WEBIRC_PASSWORD_MAX 127U
#define IRCD_WEBIRC_GATEWAY_NAME_MAX 127U

/* Operator/network-administrator storage limits. */
#define IRCD_OPER_NAME_MAX 63U
#define IRCD_OPER_HASH_MAX 255U
#define IRCD_OPER_FLAGS_MAX 255U
#define IRCD_OPER_HOSTMASK_MAX 255U
#define IRCD_OPER_VHOST_MAX IRC_HOST_MAX

/* Argon2id parameters used for OPER and NickServ credentials. */
#define IRCD_ARGON2_TIME_COST 3U
#define IRCD_ARGON2_MEMORY_COST_KIB 65536U
#define IRCD_ARGON2_PARALLELISM 1U
#define IRCD_ARGON2_SALT_BYTES 16U
#define IRCD_ARGON2_HASH_BYTES 32U

#define IRCD_SUPPORTED_USER_MODES ""
#define IRCD_SUPPORTED_CHANNEL_MODES ""
#define IRCD_ISUPPORT_BASE \
    "CASEMAPPING=rfc1459 CHANTYPES=#& NICKLEN=31 CHANNELLEN=63 MSGREFTYPES=timestamp"

#define IRCD_SERVER_NAME IRCD_DEFAULT_SERVER_NAME
#define IRCD_NETWORK_NAME IRCD_DEFAULT_NETWORK_NAME
#define IRCD_ISUPPORT IRCD_ISUPPORT_BASE

#define IRC_NICK_MAX 31U
#define IRC_USER_MAX 31U
#define IRC_REALNAME_MAX 127U
#define IRC_HOST_MAX 255U
#define IRC_IP_MAX 45U
#define IRC_INPUT_BUFFER_SIZE 4096U
#define IRC_MAX_CHANNELS_PER_CLIENT 32U
#define IRC_UNKNOWN_HOST "unknown"
#define IRC_DEFAULT_QUIT_REASON "Client quit"
#define IRC_QUIT_REASON_MAX 255U
#define IRC_AWAY_MAX 255U
#define IRCD_SHUTDOWN_REASON "Server shutting down"
#define IRC_CANNOT_SEND_NOT_MEMBER_TEXT "not on channel"
#define IRC_DEFAULT_PART_REASON "Leaving"
#define IRC_MODE_MAX_PARAMS 32U

#define IRC_CHANNEL_NAME_MAX 63U
#define IRC_CHANNEL_KEY_MAX 63U
#define IRC_CHANNEL_MASK_MAX 255U
#define IRC_CHANNEL_TOPIC_MAX 390U
#define IRC_CHANNEL_TOPIC_SETTER_MAX (IRC_NICK_MAX + IRC_USER_MAX + IRC_HOST_MAX + 3U)
#define IRC_CHANNEL_PREFIXES "#&"
#define IRC_CHANNEL_PREFIX '#'
#define IRC_NAMES_PUBLIC_MARKER '='
#define IRC_NAMES_PRIVATE_MARKER '*'
#define IRC_NAMES_BUFFER_SIZE 768U
#define IRC_DEFAULT_KICK_REASON "Kicked"
#define IRC_KICK_REASON_MAX 255U
#define IRC_JOIN_REDIRECT_MAX 4U

#endif /* IRCD_CONFIG_H */