/** @file runtime_config.c @brief Strict key=value runtime configuration loading. */
#include "runtime_config.h"
#include <arpa/inet.h>
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static char *trim(char *t){char *e;while(*t&&isspace((unsigned char)*t))++t;if(!*t)return t;e=t+strlen(t)-1;while(e>t&&isspace((unsigned char)*e))*e--='\0';return t;}
static int copy_value(char*d,size_t s,const char*v){int w=snprintf(d,s,"%s",v);return w>=0&&(size_t)w<s?0:-1;}
void runtime_config_defaults(ServerConfig*c){if(!c)return;memset(c,0,sizeof(*c));copy_value(c->server_name,sizeof(c->server_name),IRCD_DEFAULT_SERVER_NAME);copy_value(c->network_name,sizeof(c->network_name),IRCD_DEFAULT_NETWORK_NAME);copy_value(c->bind_address,sizeof(c->bind_address),IRCD_DEFAULT_BIND_ADDRESS);copy_value(c->port,sizeof(c->port),IRCD_DEFAULT_PORT);copy_value(c->tls_port,sizeof(c->tls_port),IRCD_DEFAULT_TLS_PORT);copy_value(c->motd_file,sizeof(c->motd_file),IRCD_DEFAULT_MOTD_FILE);copy_value(c->rules_file,sizeof(c->rules_file),IRCD_DEFAULT_RULES_FILE);copy_value(c->operators_db,sizeof(c->operators_db),IRCD_DEFAULT_OPERATORS_DB);copy_value(c->bans_db,sizeof(c->bans_db),IRCD_DEFAULT_BANS_DB);copy_value(c->nickserv_db,sizeof(c->nickserv_db),IRCD_DEFAULT_NICKSERV_DB);copy_value(c->chanserv_db,sizeof(c->chanserv_db),IRCD_DEFAULT_CHANSERV_DB);copy_value(c->history_db,sizeof(c->history_db),IRCD_DEFAULT_HISTORY_DB);copy_value(c->geoip_city_db,sizeof(c->geoip_city_db),IRCD_DEFAULT_GEOIP_CITY_DB);copy_value(c->geoip_asn_db,sizeof(c->geoip_asn_db),IRCD_DEFAULT_GEOIP_ASN_DB);copy_value(c->sendmail_path,sizeof(c->sendmail_path),IRCD_DEFAULT_SENDMAIL_PATH);copy_value(c->netadmin_hostmask,sizeof(c->netadmin_hostmask),"*!*@*");c->max_clients=IRCD_DEFAULT_MAX_CLIENTS;c->dns_timeout_seconds=IRCD_DEFAULT_DNS_TIMEOUT_SECONDS;c->dnsbl_timeout_seconds=IRCD_DEFAULT_DNSBL_TIMEOUT_SECONDS;c->history_limit=IRCD_DEFAULT_HISTORY_LIMIT;c->nickserv_reset_seconds=IRCD_DEFAULT_NICKSERV_RESET_SECONDS;c->nickserv_verify_seconds=IRCD_DEFAULT_NICKSERV_VERIFY_SECONDS;}
static int add_webirc_gateway(ServerConfig*c,const char*v){char x[IRCD_CONFIG_LINE_MAX],*ip,*p;struct in_addr a;struct in6_addr b;WebIrcGatewayConfig*g;if(c->webirc_gateway_count>=IRCD_MAX_WEBIRC_GATEWAYS||strlen(v)>=sizeof(x))return-1;snprintf(x,sizeof(x),"%s",v);ip=strtok(x," \t");p=strtok(NULL," \t");if(!ip||!p||strtok(NULL," \t"))return-1;if(inet_pton(AF_INET,ip,&a)!=1&&inet_pton(AF_INET6,ip,&b)!=1)return-1;g=&c->webirc_gateways[c->webirc_gateway_count];if(copy_value(g->ip,sizeof(g->ip),ip)||copy_value(g->password,sizeof(g->password),p))return-1;++c->webirc_gateway_count;return 0;}
static int add_dnsbl(ServerConfig*c,const char*v){char x[IRCD_CONFIG_LINE_MAX],*n,*z;DnsblZone*e;if(c->dnsbl_count>=IRCD_MAX_DNSBLS||strlen(v)>=sizeof(x))return-1;snprintf(x,sizeof(x),"%s",v);n=strtok(x," \t");z=strtok(NULL," \t");if(!n||!z||strtok(NULL," \t"))return-1;e=&c->dnsbls[c->dnsbl_count];if(copy_value(e->name,sizeof(e->name),n)||copy_value(e->zone,sizeof(e->zone),z))return-1;++c->dnsbl_count;return 0;}
static int set_seconds(unsigned long n,unsigned int*f){if(!n||n>604800UL)return-1;*f=(unsigned int)n;return 0;}
static int set_option(ServerConfig*c,const char*k,const char*v){char*e=NULL;unsigned long n;
#define S(name,field) if(strcmp(k,name)==0)return copy_value(c->field,sizeof(c->field),v)
if(strcmp(k,"webirc_gateway")==0)return add_webirc_gateway(c,v);if(strcmp(k,"dnsbl")==0)return add_dnsbl(c,v);S("server_name",server_name);S("network_name",network_name);S("bind_address",bind_address);S("port",port);S("tls_port",tls_port);S("tls_cert_file",tls_cert_file);S("tls_key_file",tls_key_file);S("geoip_city_db",geoip_city_db);S("geoip_asn_db",geoip_asn_db);S("server_password",server_password);S("motd_file",motd_file);S("rules_file",rules_file);S("admin_location1",admin_location1);S("admin_location2",admin_location2);S("admin_email",admin_email);S("operators_db",operators_db);S("bans_db",bans_db);S("nickserv_db",nickserv_db);S("chanserv_db",chanserv_db);S("history_db",history_db);S("sendmail_path",sendmail_path);S("mail_from",mail_from);S("netadmin_name",netadmin_name);S("netadmin_password_hash",netadmin_password_hash);S("netadmin_hostmask",netadmin_hostmask);S("netadmin_vhost",netadmin_vhost);
#undef S
errno=0;n=strtoul(v,&e,10);if(errno||e==v||*e)return-1;if(strcmp(k,"max_clients")==0){if(!n||n>IRCD_HARD_MAX_CLIENTS)return-1;c->max_clients=(size_t)n;return 0;}if(strcmp(k,"history_limit")==0){if(!n||n>IRCD_HISTORY_HARD_LIMIT)return-1;c->history_limit=(size_t)n;return 0;}if(strcmp(k,"dns_timeout_seconds")==0){if(!n||n>300)return-1;c->dns_timeout_seconds=(unsigned int)n;return 0;}if(strcmp(k,"dnsbl_timeout_seconds")==0){if(!n||n>300)return-1;c->dnsbl_timeout_seconds=(unsigned int)n;return 0;}if(strcmp(k,"nickserv_reset_seconds")==0)return set_seconds(n,&c->nickserv_reset_seconds);if(strcmp(k,"nickserv_verify_seconds")==0)return set_seconds(n,&c->nickserv_verify_seconds);return-1;}
int runtime_config_load(ServerConfig*c,const char*p){FILE*f;char l[IRCD_CONFIG_LINE_MAX];unsigned long no=0;if(!c||!p)return-1;f=fopen(p,"r");if(!f)return-1;while(fgets(l,sizeof(l),f)){char*t=trim(l),*eq,*k,*v;++no;if(!*t||*t=='#')continue;eq=strchr(t,'=');if(!eq){fprintf(stderr,"%s:%lu: expected key=value\n",p,no);fclose(f);return-1;}*eq='\0';k=trim(t);v=trim(eq+1);if(!*k||set_option(c,k,v)){fprintf(stderr,"%s:%lu: invalid option '%s'\n",p,no,k);fclose(f);return-1;}}if(ferror(f)){fclose(f);return-1;}fclose(f);copy_value(c->source_path,sizeof(c->source_path),p);return 0;}
